evaluated_languages = {"java" : dict(name="java", imperative="y", typing="s", compiled="y", functional="n", vm="jvm", game="y", phone="y", description="An object oriented language common in enterprise and android development. Has an in-depth type system with inheritance and polymorphism."),
                       "python" : dict(name="python", imperative="y", typing="d", compiled="n", functional="n", game="y", phone="y", utility="y", description="An easy to use scripting language with a number of useful features for producing succinct and powerful code. Has tools for both functional and object-oriented."),
                       "c" : dict(name="c", imperative="y", typing="s", compiled="y", functional="n", description="A relatively low-level language with many applications in embedded devices and performance-reliant software."),
                       "c++" : dict(name="c++", imperative="y", typing="s", compiled="y", functional="n", game="y", description="An expanded version of C with a more complex type system, akin to Java's. Often used in enterprise systems and video games."),
                       "c#" : dict(name="c#", imperative="y", typing="s", compiled="n", functional="n", game="y", utility="y", description="A jack-of-all-trades scripting language combining the utility of python with the object-orientedness of java."),
                       "javascript" : dict(name="javascript", imperative="y", typing="d", compiled="n", functional="n", game="y",  description="A scripting language used for adding real-time components to web-pages, such as animation and active html modification. Also used with nodeJS to program web-servers."),
                       "haskell" : dict(name="haskell", imperative="n", typing="s", compiled="y", functional="y", description="A functional language known for its extensive usage of lazy evaluation"),
                       "clojure" : dict(name="clojure", imperative="n", typing="d", compiled="y", functional="y", vm="jvm", phone="y", utility="y", description="A modern dialect of lisp running on the java virtual machine."),
                       "smalltalk" : dict(name="smalltalk", imperative="n", typing="d", compiled="y", functional="n", vm="squeakvm", description="An object-oriented programming language that stores program state in an \"image\" on the hard disk. The modtalk implementation is strongly recommended.")}
